// Boutique Wellness Blueprint - TypeScript Types
// Matches the JSON schema generated by GPT-4o in the backend

export interface BlueprintCoverPage {
  clientName: string;
  subtitle: string;
  coachingType: string;
  tagline: string;
}

export interface BlueprintExecutiveArchitecture {
  mission: string;
  identityShift: string;
  keyInsight: string;
}

export interface MindsetWeek {
  theme: string;
  focus: string;
  actionItem: string;
}

export interface BlueprintMindsetRoadmap {
  week1: MindsetWeek;
  week2: MindsetWeek;
  week3: MindsetWeek;
  week4: MindsetWeek;
}

export interface BlueprintMedicalPillar {
  overview: string;
  considerations: string[];
  adaptations: string[];
  doctorClearance: string;
}

export interface BlueprintStructuralIntegrity {
  title: string;
  primaryConcerns: string[];
  protocols: string[];
  whatToAvoid: string[];
  whatToEmbrace: string[];
}

export interface EquipmentItem {
  name: string;
  purpose: string;
  category: "Core" | "Mobility" | "Strength" | "Recovery";
}

export interface BlueprintEquipmentAudit {
  overview: string;
  essentialEquipment: EquipmentItem[];
  recommendations: string[];
}

export interface NutritionTenet {
  tenet: string;
  explanation: string;
}

export interface BlueprintNutritionBlueprint {
  philosophy: string;
  coreTenets: NutritionTenet[];
  dailyTargets: {
    calories: string;
    protein: string;
    hydration: string;
  };
  restrictions: string[];
}

export interface RecipeMacros {
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
}

export interface BlueprintRecipeCard {
  name: string;
  mealType: "breakfast" | "lunch" | "dinner" | "snack";
  tagline: string;
  whyItWorks: string;
  ingredients: string[];
  instructions: string;
  macros: RecipeMacros;
  prepTime: string;
}

export interface BlueprintData {
  coverPage: BlueprintCoverPage;
  executiveArchitecture: BlueprintExecutiveArchitecture;
  mindsetRoadmap: BlueprintMindsetRoadmap;
  medicalPillar: BlueprintMedicalPillar;
  structuralIntegrity: BlueprintStructuralIntegrity;
  equipmentAudit: BlueprintEquipmentAudit;
  nutritionBlueprint: BlueprintNutritionBlueprint;
  recipeCards: BlueprintRecipeCard[];
}

// Category colors for equipment audit
export const EQUIPMENT_CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  Core: { bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200" },
  Mobility: { bg: "bg-sky-50", text: "text-sky-700", border: "border-sky-200" },
  Strength: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200" },
  Recovery: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
};

// Meal type colors for recipe cards
export const MEAL_TYPE_COLORS: Record<string, { bg: string; text: string; border: string; icon: string }> = {
  breakfast: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200", icon: "sunrise" },
  lunch: { bg: "bg-green-50", text: "text-green-700", border: "border-green-200", icon: "sun" },
  dinner: { bg: "bg-indigo-50", text: "text-indigo-700", border: "border-indigo-200", icon: "moon" },
  snack: { bg: "bg-pink-50", text: "text-pink-700", border: "border-pink-200", icon: "cookie" },
};
